import type { Activity, Lead, WorkspaceMember } from "@/types/lead";

const MOCK_WORKSPACE_ID = "mock-workspace";

export const MOCK_MEMBERS: WorkspaceMember[] = [
  { userId: "member-ana", name: "Ana Beatriz Souza" },
  { userId: "member-carlos", name: "Carlos Eduardo Lima" },
  { userId: "member-mariana", name: "Mariana Ferreira" },
];

function daysAgo(days: number, hour = 9): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Rafael Almeida",
    email: "rafael.almeida@almeidacontabil.com.br",
    phone: "(11) 98211-4432",
    company: "Almeida Contabilidade",
    jobTitle: "Sócio-diretor",
    status: "novo",
    ownerId: "member-ana",
    source: "manual",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "lead-2",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Juliana Costa",
    email: "juliana.costa@costamkt.com.br",
    phone: "(21) 99765-1120",
    company: "Costa Marketing Digital",
    jobTitle: "Gerente de Marketing",
    status: "contatado",
    ownerId: "member-carlos",
    source: "whatsapp",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
  },
  {
    id: "lead-3",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Bruno Oliveira",
    email: "bruno.oliveira@technordeste.com",
    phone: "(81) 98811-2233",
    company: "TechNordeste Soluções",
    jobTitle: "CTO",
    status: "qualificado",
    ownerId: "member-mariana",
    source: "manual",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(3),
  },
  {
    id: "lead-4",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Fernanda Ribeiro",
    email: "fernanda.ribeiro@ribeiroadv.com.br",
    phone: "(31) 99123-4455",
    company: "Ribeiro Advocacia",
    jobTitle: "Advogada Sócia",
    status: "convertido",
    ownerId: "member-ana",
    source: "manual",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(4),
  },
  {
    id: "lead-5",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Gustavo Pereira",
    email: "gustavo.pereira@pereiraconsult.com.br",
    phone: "(41) 98877-6655",
    company: "Pereira Consultoria",
    jobTitle: "Diretor Comercial",
    status: "desqualificado",
    ownerId: "member-carlos",
    source: "manual",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(10),
  },
  {
    id: "lead-6",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Camila Santos",
    email: "camila.santos@santosstudio.com.br",
    phone: "(11) 97654-3322",
    company: "Santos Studio",
    jobTitle: "Fundadora",
    status: "novo",
    ownerId: null,
    source: "whatsapp",
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "lead-7",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Diego Martins",
    email: "diego.martins@martinslog.com.br",
    phone: "(47) 99988-7766",
    company: "Martins Logística",
    jobTitle: "Gerente de Operações",
    status: "contatado",
    ownerId: "member-mariana",
    source: "manual",
    createdAt: daysAgo(10),
    updatedAt: daysAgo(6),
  },
  {
    id: "lead-8",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Larissa Gomes",
    email: "larissa.gomes@gomesarq.com.br",
    phone: "(51) 98765-4321",
    company: "Gomes Arquitetura",
    jobTitle: "Arquiteta Sócia",
    status: "qualificado",
    ownerId: "member-ana",
    source: "manual",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
  },
  {
    id: "lead-9",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Thiago Barbosa",
    email: "thiago.barbosa@barbosacorretora.com.br",
    phone: "(85) 99111-2244",
    company: "Barbosa Corretora",
    jobTitle: "Corretor",
    status: "novo",
    ownerId: "member-carlos",
    source: "manual",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: "lead-10",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Patrícia Rocha",
    email: "patricia.rocha@rochaeducacao.com.br",
    phone: "(61) 98123-9988",
    company: "Rocha Educação",
    jobTitle: "Coordenadora Pedagógica",
    status: "contatado",
    ownerId: "member-mariana",
    source: "whatsapp",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(1),
  },
  {
    id: "lead-11",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Eduardo Nascimento",
    email: "eduardo.nascimento@nascimentotech.com.br",
    phone: "(19) 99456-7788",
    company: "Nascimento Tech",
    jobTitle: "CEO",
    status: "convertido",
    ownerId: "member-ana",
    source: "manual",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
  },
  {
    id: "lead-12",
    workspaceId: MOCK_WORKSPACE_ID,
    name: "Beatriz Cardoso",
    email: "beatriz.cardoso@cardosoeventos.com.br",
    phone: "(27) 98234-5566",
    company: "Cardoso Eventos",
    jobTitle: "Diretora de Eventos",
    status: "qualificado",
    ownerId: "member-carlos",
    source: "manual",
    createdAt: daysAgo(18),
    updatedAt: daysAgo(7),
  },
];

export const MOCK_ACTIVITIES: Record<string, Activity[]> = {
  "lead-1": [
    {
      id: "act-1-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-1",
      authorId: "member-ana",
      type: "nota",
      description: "Lead chegou via indicação de outro cliente da carteira.",
      occurredAt: daysAgo(2, 9),
      createdAt: daysAgo(2, 9),
    },
  ],
  "lead-2": [
    {
      id: "act-2-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-2",
      authorId: "member-carlos",
      type: "email",
      description: "Enviado e-mail de apresentação com material institucional.",
      occurredAt: daysAgo(5, 10),
      createdAt: daysAgo(5, 10),
    },
    {
      id: "act-2-2",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-2",
      authorId: "member-carlos",
      type: "ligacao",
      description: "Ligação de follow-up — cliente pediu retorno na próxima semana.",
      occurredAt: daysAgo(1, 14),
      createdAt: daysAgo(1, 14),
    },
  ],
  "lead-3": [
    {
      id: "act-3-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-3",
      authorId: "member-mariana",
      type: "reuniao",
      description: "Reunião de descoberta realizada por videochamada.",
      occurredAt: daysAgo(8, 11),
      createdAt: daysAgo(8, 11),
    },
    {
      id: "act-3-2",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-3",
      authorId: "member-mariana",
      type: "nota",
      description: "Cliente confirmou orçamento disponível para o próximo trimestre.",
      occurredAt: daysAgo(3, 16),
      createdAt: daysAgo(3, 16),
    },
  ],
  "lead-4": [
    {
      id: "act-4-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-4",
      authorId: "member-ana",
      type: "reuniao",
      description: "Apresentação de proposta comercial.",
      occurredAt: daysAgo(20, 9),
      createdAt: daysAgo(20, 9),
    },
    {
      id: "act-4-2",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-4",
      authorId: "member-ana",
      type: "nota",
      description: "Contrato assinado — negócio fechado com sucesso.",
      occurredAt: daysAgo(4, 15),
      createdAt: daysAgo(4, 15),
    },
  ],
  "lead-5": [
    {
      id: "act-5-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-5",
      authorId: "member-carlos",
      type: "ligacao",
      description: "Cliente informou que não tem orçamento no momento.",
      occurredAt: daysAgo(10, 10),
      createdAt: daysAgo(10, 10),
    },
  ],
  "lead-6": [],
  "lead-7": [
    {
      id: "act-7-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-7",
      authorId: "member-mariana",
      type: "email",
      description: "Enviada tabela de preços solicitada pelo cliente.",
      occurredAt: daysAgo(6, 13),
      createdAt: daysAgo(6, 13),
    },
  ],
  "lead-8": [
    {
      id: "act-8-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-8",
      authorId: "member-ana",
      type: "reuniao",
      description: "Visita técnica agendada para avaliar o projeto.",
      occurredAt: daysAgo(2, 9),
      createdAt: daysAgo(2, 9),
    },
  ],
  "lead-9": [],
  "lead-10": [
    {
      id: "act-10-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-10",
      authorId: "member-mariana",
      type: "ligacao",
      description: "Primeiro contato realizado, cliente demonstrou interesse.",
      occurredAt: daysAgo(6, 9),
      createdAt: daysAgo(6, 9),
    },
  ],
  "lead-11": [
    {
      id: "act-11-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-11",
      authorId: "member-ana",
      type: "nota",
      description: "Renovação de contrato fechada para mais 12 meses.",
      occurredAt: daysAgo(5, 17),
      createdAt: daysAgo(5, 17),
    },
  ],
  "lead-12": [
    {
      id: "act-12-1",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-12",
      authorId: "member-carlos",
      type: "email",
      description: "Enviado portfólio de eventos já realizados.",
      occurredAt: daysAgo(18, 10),
      createdAt: daysAgo(18, 10),
    },
    {
      id: "act-12-2",
      workspaceId: MOCK_WORKSPACE_ID,
      leadId: "lead-12",
      authorId: "member-carlos",
      type: "reuniao",
      description: "Reunião de alinhamento de escopo do evento.",
      occurredAt: daysAgo(7, 14),
      createdAt: daysAgo(7, 14),
    },
  ],
};
