import type { Deal } from "@/types/deal";

const MOCK_WORKSPACE_ID = "mock-workspace";

function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(12, 0, 0, 0);
  return date.toISOString();
}

export const MOCK_DEALS: Deal[] = [
  {
    id: "deal-1",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Plano Pro — Almeida Contabilidade",
    value: 4900,
    leadId: "lead-1",
    ownerId: "member-ana",
    stage: "novo_lead",
    dueDate: daysFromNow(6),
    createdAt: daysFromNow(-2),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "deal-2",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Consultoria de vendas — Santos Studio",
    value: 3200,
    leadId: "lead-6",
    ownerId: null,
    stage: "novo_lead",
    dueDate: daysFromNow(9),
    createdAt: daysFromNow(-1),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "deal-3",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Licença anual — Costa Marketing Digital",
    value: 8400,
    leadId: "lead-2",
    ownerId: "member-carlos",
    stage: "contato_realizado",
    dueDate: daysFromNow(4),
    createdAt: daysFromNow(-5),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "deal-4",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Implantação CRM — Martins Logística",
    value: 12500,
    leadId: "lead-7",
    ownerId: "member-mariana",
    stage: "contato_realizado",
    dueDate: daysFromNow(-2),
    createdAt: daysFromNow(-10),
    updatedAt: daysFromNow(-6),
  },
  {
    id: "deal-5",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Upgrade de plano — TechNordeste Soluções",
    value: 15800,
    leadId: "lead-3",
    ownerId: "member-mariana",
    stage: "proposta_enviada",
    dueDate: daysFromNow(3),
    createdAt: daysFromNow(-8),
    updatedAt: daysFromNow(-3),
  },
  {
    id: "deal-6",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Projeto de automação — Gomes Arquitetura",
    value: 6700,
    leadId: "lead-8",
    ownerId: "member-ana",
    stage: "proposta_enviada",
    dueDate: daysFromNow(11),
    createdAt: daysFromNow(-12),
    updatedAt: daysFromNow(-2),
  },
  {
    id: "deal-7",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Contrato anual — Rocha Educação",
    value: 9200,
    leadId: "lead-10",
    ownerId: "member-mariana",
    stage: "negociacao",
    dueDate: daysFromNow(-1),
    createdAt: daysFromNow(-6),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "deal-8",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Pacote corporativo — Barbosa Corretora",
    value: 5400,
    leadId: "lead-9",
    ownerId: "member-carlos",
    stage: "negociacao",
    dueDate: daysFromNow(7),
    createdAt: daysFromNow(-3),
    updatedAt: daysFromNow(-1),
  },
  {
    id: "deal-9",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Renovação de contrato — Ribeiro Advocacia",
    value: 7300,
    leadId: "lead-4",
    ownerId: "member-ana",
    stage: "fechado_ganho",
    dueDate: daysFromNow(-4),
    createdAt: daysFromNow(-20),
    updatedAt: daysFromNow(-4),
  },
  {
    id: "deal-10",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Renovação anual — Nascimento Tech",
    value: 21000,
    leadId: "lead-11",
    ownerId: "member-ana",
    stage: "fechado_ganho",
    dueDate: daysFromNow(-5),
    createdAt: daysFromNow(-30),
    updatedAt: daysFromNow(-5),
  },
  {
    id: "deal-11",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Plano Starter — Pereira Consultoria",
    value: 2900,
    leadId: "lead-5",
    ownerId: "member-carlos",
    stage: "fechado_perdido",
    dueDate: daysFromNow(-10),
    createdAt: daysFromNow(-15),
    updatedAt: daysFromNow(-10),
  },
  {
    id: "deal-12",
    workspaceId: MOCK_WORKSPACE_ID,
    title: "Consultoria pontual — Cardoso Eventos",
    value: 4100,
    leadId: "lead-12",
    ownerId: "member-carlos",
    stage: "fechado_perdido",
    dueDate: daysFromNow(-8),
    createdAt: daysFromNow(-18),
    updatedAt: daysFromNow(-7),
  },
];
